### PR TITLE
Fix/transaction

### PR DESCRIPTION
**Pull request by Radiateurs**
Adding transactions history and CRUD methods on it

### CODE REVIEW

**Comment by chekroA** [comment]
Elle est due à ce que tu as mis dans ton model de transfer

**Comment by chekroA** [comment]
lesson = models.ForeignKey(LessonSubscription, on_delete=models.DO_NOTHING, null=True)

->

lesson = models.ForeignKey(LessonSubscription, on_delete=models.SET_NULL, null=True)

**Comment by Radiateurs** [comment]
Done :)

**Comment by chekroA** [comment]
Postman plz 😉

**Pull request merged**
